# configs/train_river.yml
{
  ### Environment Parameters
  debug: false,
  mode: train,
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 8,
  log_interval: 9999,
  save_interval: 1,
  saved_model_directory: 'river_models',
  train_fold: 1,
  project_name: 'River-Water-Segmentation',
  CUDA_VISIBLE_DEVICES: '0',

  ### Train Parameters
  model_name: 'FSGNet',
    n_classes: 1,
    in_channels: 3,
    base_c: 64,
    depths: [3, 3, 9, 3],
    kernel_size: 7,
  dataloader: 'Image2Image_resize',
  criterion: 'DiceBCELoss',
  task: 'segmentation',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [512, 512],
  optimizer: 'AdamW',
    lr: 0.001,
    scheduler: 'WarmupCosine',
    cycles: 100,
    warmup_epoch: 10,
    weight_decay: 0.01,
  batch_size: 8,
  epoch: 500,
  ema_decay: 0,
  class_weight: [1.0, 1.0],
  model_path: '',
    freeze_layer: false,

  ### Augmentation Parameters
  transform_blur: true,
  transform_jitter: true,
  transform_hflip: true,
  transform_perspective: false,
  transform_cutmix: true,
  transform_rand_resize: true,
  transform_rand_crop: 256,

  ### 数据路径
  train_x_path: 'data/RIVER/train/images',
  train_y_path: 'data/RIVER/train/masks',
  val_x_path: 'data/RIVER/val/images',
  val_y_path: 'data/RIVER/val/masks',
}