### Environment Parameters
debug: false
mode: inference
cuda: true
pin_memory: true
wandb: false
worker: 2
CUDA_VISIBLE_DEVICES: '0'

### Train Parameters
model_name: 'FSGNet'
n_classes: 1
in_channels: 3
base_c: 64
inference_mode: 'segmentation'
task: 'segmentation'
dataloader: 'Image2Image_resize'
criterion: 'DiceBCE'
input_space: 'RGB'
input_channel: 3

# 数据集特定参数 - 根据您使用的数据集取消注释对应部分
# DRIVE数据集
input_size: [608, 608]
model_path: '/root/FSG-Net-pytorch/model_ckpts/FSG-Net-DRIVE.pt'
val_x_path: "/root/FSG-Net-pytorch/data/DRIVE/val/input"
val_y_path: "/root/FSG-Net-pytorch/data/DRIVE/val/label"

# STARE数据集
# input_size: [704, 704]
# model_path: 'E:/temp/FSG-Net-pytorch/model_ckpts/FSG-Net_STARE.pth'
# val_x_path: 'E:/temp/FSG-Net-pytorch/data/STARE/val/input'
# val_y_path: 'E:/temp/FSG-Net-pytorch/data/STARE/val/label'

# CHASE_DB1数据集
# input_size: [1024, 1024]
# model_path: 'E:/temp/FSG-Net-pytorch/model_ckpts/FSG-Net_CHASE_DB1.pth'
# val_x_path: 'E:/temp/FSG-Net-pytorch/data/CHASE_DB1/val/input'
# val_y_path: 'E:/temp/FSG-Net-pytorch/data/CHASE_DB1/val/label'

# HRF数据集
# input_size: [1344, 1344]
# model_path: 'E:/temp/FSG-Net-pytorch/model_ckpts/FSG-Net_HRF.pth'
# val_x_path: 'E:/temp/FSG-Net-pytorch/data/HRF/val/input'
# val_y_path: 'E:/temp/FSG-Net-pytorch/data/HRF/val/label'