{
  debug: False,
  mode: 'train',
  cuda: True,
  pin_memory: True,
  wandb: False,
  worker: 4,
  log_interval: 9999,
  save_interval: 1,
  saved_model_directory: 'quick_test_models',
  train_fold: 1,
  project_name: 'QuickTest',
  CUDA_VISIBLE_DEVICES: '0',
  model_name: 'UNet',
  n_classes: 1,
  in_channels: 3,
  base_c: 64,
  depths: [3, 3, 9, 3],
  kernel_size: 11,
  dataloader: 'Image2Image_resize',
  criterion: 'FocalDiceLoss',
  task: 'segmentation',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [512, 512],
  optimizer: 'AdamW',
  lr: 0.0005,
  scheduler: 'WarmupCosine',
  cycles: 100,
  warmup_epoch: 5,
  weight_decay: 0.01,
  batch_size: 2,
  epoch: 500,
  ema_decay: 0,
  class_weight: [0.3, 0.7],
  model_path: '',
  freeze_layer: False,
  transform_blur: True,
  transform_jitter: True,
  transform_hflip: True,
  transform_perspective: False,
  transform_cutmix: True,
  transform_rand_resize: True,
  transform_rand_crop: 256,
  train_x_path: 'quick_test_data/train/images',
  train_y_path: 'quick_test_data/train/masks',
  val_x_path: 'quick_test_data/val/images',
  val_y_path: 'quick_test_data/val/masks',
}