python3 main.py --config_path "configs/UNet_train.yml"
python3 main.py --config_path "configs/agnet_train.yml"
python3 main.py --config_path "configs/rgfsg_train.yml"
python3 main.py --config_path "configs/gemfsg_train.yml"
python3 main.py --config_path "configs/rgemfsg_train.yml"
python3 main.py --config_path "configs/dual-fsgnet.yml"
python3 main.py --config_path "configs/dual-unet2p.yml"
python3 main.py --config_path "configs/train_fsgnet_input_guided_v3.yml"
python3 main.py --config_path "configs/train_fsgnet_encoder_guided.yml"

